### ISSUE TITLE
M1/ARM/macOS issues

### ISSUE THREAD

**Issue by longshorej** [pantomime-rs/pantomime#77]
Thread for issues when running on new Apple hardware. In general, if it turns out that these issues are due to some dependency, prefer to remove that dependency rather than upgrade.

**Comment by longshorej** [comment]
```
thread '<unnamed>' panicked at 'attempted to leave type `internal::Local` uninitialized, which is invalid', /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/mem/mod.rs:660:9
thread '<unnamed>' panicked at 'attempted to leave type `internal::Local` uninitialized, which is invalid', /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/mem/mod.rs:660:9
thread '<unnamed>' panicked at 'attempted to leave type `internal::Local` uninitialized, which i
```

**Comment by longshorej** [comment]
```
kill: unknown signal 10; valid signals:
HUP INT QUIT ILL TRAP ABRT EMT FPE KILL BUS SEGV SYS PIPE ALRM TERM URG
STOP TSTP CONT CHLD TTIN TTOU IO XCPU XFSZ VTALRM PROF WINCH INFO USR1 USR2
^C
```
